-- ═══════════════════════════════════════════════════════════════════════
--  VOID — Pure black & white
--  Designed for colorblindness + ADHD: zero chroma, weight carries meaning
--  Bold → structural (keywords, functions, types)
--  Italic → secondary (comments, parameters)
--  Normal → content (variables, strings, literals)
--  Dim → noise (punctuation, non-text)
-- ═══════════════════════════════════════════════════════════════════════

vim.cmd('highlight clear')
vim.g.colors_name = 'void'

-- Palette: 6 luminance stops, zero chroma
local bg      = '#000000'
local surface = '#0d0d0d'  -- CursorLine only — minimum visible lift on OLED
local overlay = '#111111'  -- Pmenu — needs to float above text
local muted   = '#333333'
local dim     = '#666666'
local fg      = '#cccccc'
local bright  = '#ffffff'

local hl = function(name, opts) vim.api.nvim_set_hl(0, name, opts) end

-- ── Editor UI ────────────────────────────────────────────────────────
hl('Normal',         { fg = fg,     bg = bg })
hl('NormalFloat',    { fg = fg,     bg = bg })
hl('FloatBorder',    { fg = dim,    bg = bg })
hl('FloatTitle',     { fg = bright, bg = bg, bold = true })
hl('CursorLine',     { bg = surface })
hl('CursorLineNr',   { fg = bright, bold = true })
hl('LineNr',         { fg = dim })
hl('SignColumn',     { bg = bg })
hl('VertSplit',      { fg = muted })
hl('WinSeparator',   { fg = muted })
hl('StatusLine',     { fg = dim,    bg = bg })
hl('StatusLineNC',   { fg = muted,  bg = bg })
hl('TabLine',        { fg = dim,    bg = bg })
hl('TabLineFill',    { bg = bg })
hl('TabLineSel',     { fg = bright, bg = bg, bold = true })
hl('Pmenu',          { fg = fg,     bg = overlay })
hl('PmenuSel',       { fg = bright, bg = muted, bold = true })
hl('PmenuSbar',      { bg = muted })
hl('PmenuThumb',     { bg = dim })
hl('Visual',         { fg = bg,     bg = '#888888' })
hl('VisualNOS',      { bg = muted })
hl('Search',         { fg = bg,     bg = dim })
hl('IncSearch',      { fg = bg,     bg = bright, bold = true })
hl('CurSearch',      { fg = bg,     bg = '#aaaaaa', bold = true })
hl('Substitute',     { fg = bg,     bg = fg })
hl('MatchParen',     { fg = bright, bold = true })
hl('BracketScope',   { bg = bg })
hl('Folded',         { fg = dim,    bg = bg })
hl('FoldColumn',     { fg = dim,    bg = bg })
hl('NonText',        { fg = '#3a3a3a' })
hl('SpecialKey',     { fg = muted })
hl('Whitespace',     { fg = '#3a3a3a' })
hl('EndOfBuffer',    { fg = bg })
hl('Directory',      { fg = dim })
hl('Title',          { fg = bright, bold = true })
hl('ErrorMsg',       { fg = bright, bold = true, underline = true })
hl('WarningMsg',     { fg = fg,     bold = true })
hl('MoreMsg',        { fg = fg })
hl('MsgSeparator',   { fg = fg,     bg = muted })
hl('ModeMsg',        { fg = fg,     bold = true })
hl('Question',       { fg = dim })
hl('WildMenu',       { fg = bright, bg = muted })
hl('Conceal',        { fg = dim })
hl('ColorColumn',    { bg = bg })
hl('QuickFixLine',   { fg = fg, bold = true })
hl('WinBar',         { fg = fg,     bg = bg, bold = true })
hl('WinBarNC',       { fg = dim,    bg = bg })
hl('Cursor',         { fg = bg,     bg = fg })
hl('lCursor',        { fg = bg,     bg = fg })
hl('CursorIM',       { fg = bg,     bg = fg })
hl('TermCursor',     { fg = bg,     bg = fg })
hl('TermCursorNC',   { fg = bg,     bg = dim })

-- ── Syntax (traditional Vim groups) ─────────────────────────────────
hl('Comment',        { fg = dim, italic = true })
hl('Constant',       { fg = fg })
hl('String',         { fg = '#d4d4d4' })
hl('Character',      { fg = fg })
hl('Number',         { fg = fg })
hl('Boolean',        { fg = bright, bold = true })
hl('Float',          { fg = fg })
hl('Identifier',     { fg = fg })
hl('Function',       { fg = bright, bold = true })
hl('Statement',      { fg = bright, bold = true })
hl('Conditional',    { fg = bright, bold = true })
hl('Repeat',         { fg = bright, bold = true })
hl('Label',          { fg = bright, bold = true })
hl('Operator',       { fg = fg })
hl('Keyword',        { fg = bright, bold = true })
hl('Exception',      { fg = bright, bold = true })
hl('PreProc',        { fg = bright, bold = true })
hl('Include',        { fg = bright, bold = true })
hl('Define',         { fg = bright, bold = true })
hl('Macro',          { fg = bright, bold = true })
hl('PreCondit',      { fg = bright, bold = true })
hl('Type',           { fg = bright, bold = true })
hl('StorageClass',   { fg = bright, bold = true })
hl('Structure',      { fg = bright, bold = true })
hl('Typedef',        { fg = bright, bold = true })
hl('Special',        { fg = fg })
hl('SpecialChar',    { fg = fg })
hl('Tag',            { fg = bright, bold = true })
hl('Delimiter',      { fg = dim })
hl('SpecialComment', { fg = dim, italic = true, bold = true })
hl('Debug',          { fg = fg })
hl('Underlined',     { fg = fg, underline = true })
hl('Ignore',         { fg = muted })
hl('Error',          { fg = bright, bold = true, underline = true })
hl('Todo',           { fg = bright, bg = muted, bold = true })
hl('Added',          { fg = fg, bold = true })
hl('Changed',        { fg = fg, italic = true })
hl('Removed',        { fg = dim, strikethrough = true })

-- ── Treesitter ──────────────────────────────────────────────────────
hl('@comment',                { fg = dim, italic = true })
hl('@comment.documentation',  { fg = dim, italic = true })
hl('@comment.todo',           { fg = bright, bg = muted, bold = true })
hl('@comment.note',           { fg = fg, italic = true, bold = true })
hl('@comment.warning',        { fg = bg, bg = fg, bold = true })
hl('@comment.error',          { fg = bg, bg = bright, bold = true })

hl('@keyword',                { fg = bright, bold = true })
hl('@keyword.function',       { fg = bright, bold = true })
hl('@keyword.return',         { fg = bright, bold = true })
hl('@keyword.operator',       { fg = fg })
hl('@keyword.import',         { fg = bright, bold = true })
hl('@keyword.export',         { fg = bright, bold = true })
hl('@keyword.modifier',       { fg = bright, bold = true })
hl('@keyword.conditional',    { fg = bright, bold = true })
hl('@keyword.repeat',         { fg = bright, bold = true })
hl('@keyword.exception',      { fg = bright, bold = true })

hl('@function',               { fg = bright, bold = true })
hl('@function.call',          { fg = fg, bold = true })
hl('@function.builtin',       { fg = fg, bold = true })
hl('@function.method',        { fg = bright, bold = true })
hl('@function.method.call',   { fg = fg, bold = true })
hl('@constructor',            { fg = bright, bold = true })

hl('@variable',               { fg = fg })
hl('@variable.builtin',       { fg = fg, italic = true })
hl('@variable.parameter',     { fg = fg, italic = true })
hl('@variable.member',        { fg = fg })

hl('@constant',               { fg = fg, bold = true })
hl('@constant.builtin',       { fg = fg, bold = true })
hl('@constant.macro',         { fg = fg, bold = true })

hl('@type',                   { fg = bright, bold = true })
hl('@type.builtin',           { fg = bright, bold = true })
hl('@type.qualifier',         { fg = bright, bold = true })
hl('@type.definition',        { fg = bright, bold = true })

hl('@string',                 { fg = '#d4d4d4' })
hl('@string.documentation',   { fg = dim })
hl('@string.escape',          { fg = fg, bold = true })
hl('@string.regex',           { fg = fg, bold = true })
hl('@string.special',         { fg = fg })
hl('@number',                 { fg = fg })
hl('@number.float',           { fg = fg })
hl('@boolean',                { fg = bright, bold = true })
hl('@character',              { fg = fg })

hl('@operator',               { fg = fg })
hl('@punctuation.bracket',    { fg = dim })
hl('@punctuation.delimiter',  { fg = dim })
hl('@punctuation.special',    { fg = fg })

hl('@property',               { fg = fg })
hl('@attribute',              { fg = fg, italic = true })
hl('@label',                  { fg = bright, bold = true })
hl('@namespace',              { fg = fg, bold = true })
hl('@module',                 { fg = fg, bold = true })

hl('@tag',                    { fg = bright, bold = true })
hl('@tag.attribute',          { fg = fg })
hl('@tag.delimiter',          { fg = dim })
hl('@markup.heading',         { fg = bright, bold = true })
hl('@markup.strong',          { bold = true })
hl('@markup.italic',          { italic = true })
hl('@markup.strikethrough',   { strikethrough = true })
hl('@markup.underline',       { underline = true })
hl('@markup.link',            { fg = fg, underline = true })
hl('@markup.link.url',        { fg = dim, underline = true })
hl('@markup.raw',             { fg = fg })
hl('@markup.list',            { fg = dim })

-- ── LSP semantic tokens (disabled for perf but styled if on) ────────
hl('@lsp.type.namespace',     { fg = fg, bold = true })
hl('@lsp.type.type',          { fg = bright, bold = true })
hl('@lsp.type.class',         { fg = bright, bold = true })
hl('@lsp.type.enum',          { fg = bright, bold = true })
hl('@lsp.type.interface',     { fg = bright, bold = true })
hl('@lsp.type.struct',        { fg = bright, bold = true })
hl('@lsp.type.parameter',     { fg = fg, italic = true })
hl('@lsp.type.property',      { fg = fg })
hl('@lsp.type.function',      { fg = bright, bold = true })
hl('@lsp.type.method',        { fg = bright, bold = true })
hl('@lsp.type.macro',         { fg = bright, bold = true })
hl('@lsp.type.decorator',     { fg = fg, italic = true })
hl('@lsp.type.variable',      { fg = fg })
hl('@lsp.type.enumMember',    { fg = fg, bold = true })
hl('@lsp.mod.deprecated',     { strikethrough = true })
hl('@lsp.mod.readonly',       { bold = true })

-- ── Diagnostics ─────────────────────────────────────────────────────
hl('DiagnosticError',              { fg = '#999999' })
hl('DiagnosticWarn',               { fg = '#777777' })
hl('DiagnosticInfo',               { fg = dim })
hl('DiagnosticHint',               { fg = dim, italic = true })
hl('DiagnosticUnnecessary',        { fg = '#555555' })
hl('DiagnosticUnderlineError',     { sp = '#777777', undercurl = true })
hl('DiagnosticUnderlineWarn',      { sp = dim,       underdotted = true })
hl('DiagnosticUnderlineInfo',      { sp = muted,     underdotted = true })
hl('DiagnosticUnderlineHint',      { sp = muted,     underdotted = true })
hl('DiagnosticVirtualTextError',   { fg = '#999999' })
hl('DiagnosticVirtualTextWarn',    { fg = '#777777' })
hl('DiagnosticVirtualTextInfo',    { fg = dim })
hl('DiagnosticVirtualTextHint',    { fg = dim, italic = true })
hl('DiagnosticSignError',          { fg = '#999999' })
hl('DiagnosticSignWarn',           { fg = '#777777' })
hl('DiagnosticSignInfo',           { fg = dim })
hl('DiagnosticSignHint',           { fg = dim })
hl('DiagnosticFloatingError',      { fg = fg })
hl('DiagnosticFloatingWarn',       { fg = fg })
hl('DiagnosticFloatingInfo',       { fg = dim })
hl('DiagnosticFloatingHint',       { fg = dim })

-- ── LSP references / inlay ──────────────────────────────────────────
hl('LspReferenceText',   { bg = muted })
hl('LspReferenceRead',   { bg = muted })
hl('LspReferenceWrite',  { bg = muted, bold = true })
hl('LspReferenceTarget', { bg = 'None' })
hl('LspInlayHint',       { fg = dim, italic = true })
hl('LspCodeLens',        { fg = dim, italic = true })
hl('LspSignatureActiveParameter', { bg = 'None' })

-- ── Snippet ─────────────────────────────────────────────────────────
hl('SnippetTabstop',     { fg = bg, bg = '#aaaaaa' })

-- ── Diff (grayscale only) ───────────────────────────────────────────
hl('DiffAdd',     { bg = bg })
hl('DiffChange',  { bg = bg })
hl('DiffDelete',  { fg = dim })
hl('DiffText',    { bg = surface,  bold = true })

-- ── Git blame ghost text ────────────────────────────────────────────
hl('GhostBlame',  { fg = '#555555', italic = true })
hl('GhostBlameHash',    { fg = '#4a4a4a', italic = true })
hl('GhostBlameAuthor',  { fg = '#7a7a7a', italic = true })
hl('GhostBlameMeta',    { fg = '#5c5c5c', italic = true })
hl('GhostBlameSummary', { fg = '#666666', italic = true })

-- ── Gitsigns (subtle modified-line indicators) ─────────────────────
hl('GitSignsAdd',              { fg = muted })
hl('GitSignsChange',           { fg = muted })
hl('GitSignsDelete',           { fg = muted })
hl('GitSignsTopdelete',        { fg = muted })
hl('GitSignsChangedelete',     { fg = muted })
hl('GitSignsUntracked',        { fg = muted })
hl('GitSignsAddNr',            { fg = muted })
hl('GitSignsChangeNr',         { fg = muted })
hl('GitSignsDeleteNr',         { fg = muted })
hl('GitSignsStagedAdd',        { fg = '#222222' })
hl('GitSignsStagedChange',     { fg = '#222222' })
hl('GitSignsStagedDelete',     { fg = '#222222' })
hl('GitSignsStagedChangedelete', { fg = '#222222' })
hl('GitSignsStagedTopdelete',  { fg = '#222222' })
hl('GitSignsStagedUntracked',  { fg = '#222222' })

-- ── Statusline custom groups ────────────────────────────────────────
hl('statusline_file',             { fg = '#eeeeee', bg = 'None', bold = true })
hl('statusline_modifiedfile',     { fg = '#eeeeee', bg = 'None', bold = true, italic = true })
hl('statusline_diagnostics',      { fg = dim,       bg = 'None' })
hl('statusline_separator',        { fg = muted,     bg = 'None' })
hl('statusline_misc',             { fg = muted,     bg = 'None' })
hl('statusline_branch',           { fg = dim,       bg = 'None' })
hl('statusline_mode',             { fg = dim,       bg = 'None', bold = true })
